-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgHQFBUINrHW8dS4pAfctBMEVxF36jDiUpgxhbVgoER0WgCgYIKoZIzj0DAQehRANCAATObtg9ZsVtS1ZqY8V55qlQXhDauIdgAUBPEHY/MSx0p/ojbLpSZtThZBxe/WxQET2nGApqhdKGIIeYs5FbpWEl
-----END PRIVATE KEY-----